//
//  FavoriteViewController.swift
//  E-commerce-Swift
//
//  Created by Asim Seferli on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteDisplayLogic: class
{
  func displaySomething(viewModel: Favorite.Something.ViewModel)
}

class FavoriteViewController: UIViewController, FavoriteDisplayLogic
{
  var interactor: FavoriteBusinessLogic?
  var router: (NSObjectProtocol & FavoriteRoutingLogic & FavoriteDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = FavoriteInteractor()
    let presenter = FavoritePresenter()
    let router = FavoriteRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Favorite.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Favorite.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
