//
//  FavoritePresenter.swift
//  E-commerce-Swift
//
//  Created by Asim Seferli on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritePresentationLogic
{
  func presentSomething(response: Favorite.Something.Response)
}

class FavoritePresenter: FavoritePresentationLogic
{
  weak var viewController: FavoriteDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Favorite.Something.Response)
  {
    let viewModel = Favorite.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
