//
//  PickerDetailInteractor.swift
//  E-commerce-Swift
//
//  Created by Asim Seferli on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PickerDetailBusinessLogic
{
  func doSomething(request: PickerDetail.Something.Request)
}

protocol PickerDetailDataStore
{
  //var name: String { get set }
}

class PickerDetailInteractor: PickerDetailBusinessLogic, PickerDetailDataStore
{
  var presenter: PickerDetailPresentationLogic?
  var worker: PickerDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PickerDetail.Something.Request)
  {
    worker = PickerDetailWorker()
    worker?.doSomeWork()
    
    let response = PickerDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
