//
//  PickerDetailPresenter.swift
//  E-commerce-Swift
//
//  Created by Asim Seferli on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PickerDetailPresentationLogic
{
  func presentSomething(response: PickerDetail.Something.Response)
}

class PickerDetailPresenter: PickerDetailPresentationLogic
{
  weak var viewController: PickerDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PickerDetail.Something.Response)
  {
    let viewModel = PickerDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
