//
//  ProductDetailInteractor.swift
//  E-commerce-Swift
//
//  Created by Asim Seferli on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailBusinessLogic
{
  func doSomething(request: ProductDetail.Something.Request)
}

protocol ProductDetailDataStore
{
  //var name: String { get set }
}

class ProductDetailInteractor: ProductDetailBusinessLogic, ProductDetailDataStore
{
  var presenter: ProductDetailPresentationLogic?
  var worker: ProductDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ProductDetail.Something.Request)
  {
    worker = ProductDetailWorker()
    worker?.doSomeWork()
    
    let response = ProductDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
