//
//  BusketInteractor.swift
//  E-commerce-Swift
//
//  Created by Asim Seferli on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BusketBusinessLogic
{
  func doSomething(request: Busket.Something.Request)
}

protocol BusketDataStore
{
  //var name: String { get set }
}

class BusketInteractor: BusketBusinessLogic, BusketDataStore
{
  var presenter: BusketPresentationLogic?
  var worker: BusketWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Busket.Something.Request)
  {
    worker = BusketWorker()
    worker?.doSomeWork()
    
    let response = Busket.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
